services:
  bwmDB:
    image: arm64v8/mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: "bwm"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
